before_script:
  - source ~/.bashrc
  - nvm --version
  - nvm install 4.1 2>/dev/null
  - npm --version
  - npm config set strict-ssl false
  - npm config set registry $NPM_REGISTRY_MIRROR
  - npm install
  - npm install -g bower gulp
  - bower install

stages:
  - build

build:
  stage: build
  script:
    - gulp
  only:
    - master
  tags:
    - node
    - nvm

variables:
  NVM_NODEJS_ORG_MIRROR: "https://npm.taobao.org/mirrors/node"
  NVM_IOJS_ORG_MIRROR: "https://npm.taobao.org/mirrors/iojs"
  NPM_REGISTRY_MIRROR: "https://registry.npm.taobao.org/"

cache:
  untracked: true
  paths:
    - bower_components/
    - node_modules/
